services:
  webpage_service_api:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_webpage_service_api_docker
    build:
      context: .
      dockerfile: ./dockerfiles/api_docker.dockerfile
    networks:
      - peerprep_network
    ports:
      - '9010:9010'

networks:
  peerprep_network:
    name: peerprep
    external: true
