apiVersion: v1
kind: Service
metadata:
  name: webpage-service-api-service
  namespace: peerprep
spec:
  selector:
    app: webpage-service-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010
